[package]
name = "tiktoken_crystal"
version = "0.1.0"
edition = "2021"
authors = ["kojix2 <2xijok@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }
tiktoken-rs = { git = "https://github.com/zurawiki/tiktoken-rs" }
