name: test

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.os }} / Crystal ${{ matrix.crystal }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        crystal: [latest]
    steps:
      - uses: actions/checkout@v7
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install native library
        run: crystal run scripts/install.cr
      - name: Run specs
        run: crystal spec
