name: test
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }} Crystal ${{ matrix.crystal }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:   [ 'ubuntu', 'macos' ]
        crystal: [ '1.9' ]
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Run tests
        run: |
          make test
